#配置连个EurekaServer
#一个9000， 一个8000

server:
  port: 9000

spring:
  application:
    name: eureka-server

#配置eureka server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将自己注册到注册中心，默认true
    fetch-registry: false #是否从eureka中获取注册信息，默认true
    service-url: # 配置暴露给eureka client 的请求地址
      defaultZone: http://127.0.0.1:9000/eureka/
  server:
#    enable-self-preservation: false #默认true, false为关闭自我保护机制
#    eviction-interval-timer-in-ms: 4000 #单位毫秒 剔除服务间隔
